# Specific branch context for beta building
[context.beta] # 'beta' is the branch name
  command = "jekyll build"
  publish = "_site"
  # TODO: set the base directory to 2019/

# Redirect from root domain to the summershow subdomain.
[[redirects]]
  from = "https://imperialdyson.uk/*"
  to = "https://summershow.imperialdyson.uk/:splat"
  force = true # redirect applied regardless if if there's a file already existing
