# Specific branch context for beta builds
[context.beta] # branch 'beta'
  base  = "2019/"
  command = "bundle exec jekyll build"
  publish = "_site"

[context."2019"] # branch '2019'
  base  = "2019/"
  command = "bundle exec jekyll build"
  publish = "2019/_site"

# Redirect from root domain to the summershow subdomain.
[[redirects]]
  from = "https://imperialdyson.uk/*"
  to = "https://summershow.imperialdyson.uk/:splat"
  force = true # redirect applied regardless if if there's a file already existing
